### ISSUE TITLE
hd_oldlinux.img reg

### ISSUE THREAD

**Issue by awcator** [mariuz/linux-0.01#8]
Helllo, Thanks for the project. I am able compile and run. But how did you build this file hd_oldlinux.img? I see vim installed with version 7.x

**Comment by mariuz** [comment]
you will have to build the program :
- in elf binary format
- don't forget to do a static link, because linux don't use shared library ;)
- don't forget to use option -nostdlib and -nostdinc. We can't use the std lib of the host !
- you can use function which are in lib folder, and in include folder.
- you can use dietlibc ( and maybe uclibc )
- 
http://draconux.free.fr/os_dev/linux0.01.html

and related 
https://mapopa.blogspot.com/2008/09/linux-0.html
